version: '3.7'
services:
  tftpd:
    # Allow binding of port < 1024 by regular user
    image: hongkongkiwi/tftpd-server:latest
    cap_add:
      - CAP_NET_BIND_SERVICE
    ports:
      - 69:69/udp
    environment:
      - TFTPD_LOGLEVEL=debug
    volumes:
      - ./tftpd:/tftpd
